export const UI_LABELS: Record<string, string> = {
  active: "활성",
  paused: "일시 중지",
  archived: "보관됨",
  idle: "대기",
  running: "실행 중",
  error: "오류",
  pending_approval: "승인 대기",
  terminated: "종료됨",
  backlog: "백로그",
  todo: "할 일",
  in_progress: "진행 중",
  in_review: "검토 중",
  done: "완료",
  blocked: "차단됨",
  cancelled: "취소됨",
  planned: "계획됨",
  achieved: "달성됨",
  completed: "완료",
  pending: "대기 중",
  revision_requested: "수정 요청",
  approved: "승인됨",
  rejected: "거절됨",
  company: "회사",
  team: "팀",
  agent: "에이전트",
  task: "작업",
  goal: "목표",
  project: "프로젝트",
  critical: "긴급",
  high: "높음",
  medium: "보통",
  low: "낮음",
  hire_agent: "에이전트 채용",
  approve_ceo_strategy: "CEO 전략 승인",
  budget_override_required: "예산 초과 승인",
  received: "수신됨",
  coalesced: "병합됨",
  skipped: "건너뜀",
  issue_created: "이슈 생성됨",
  failed: "실패",
  queued: "대기열",
  succeeded: "성공",
  timed_out: "시간 초과",
  disabled: "비활성",
  open: "열림",
  resolved: "해결됨",
  dismissed: "해제됨",
};

export function labelForKey(value: string): string {
  return UI_LABELS[value] ?? value.replace(/_/g, " ");
}
